# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='eda',
            field=models.IntegerField(default=0, verbose_name='EDA'),
        ),
        migrations.AddField(
            model_name='data',
            name='seconds',
            field=models.IntegerField(default=0, verbose_name='Seconds'),
        ),
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.IntegerField(default=0, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='data',
            name='unknown',
            field=models.IntegerField(default=0, verbose_name='Unknown'),
        ),
        migrations.AddField(
            model_name='data',
            name='x_coord',
            field=models.IntegerField(default=0, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='data',
            name='y_coord',
            field=models.IntegerField(default=0, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='data',
            name='z_coord',
            field=models.IntegerField(default=0, verbose_name='Z'),
        ),
    ]
