# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_', '0004_auto_20160218_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of trial')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='data_text',
            field=models.CharField(max_length=270, verbose_name='Piece of data'),
        ),
        migrations.AddField(
            model_name='data',
            name='trial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_.Trial'),
        ),
    ]
