# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_', '0005_auto_20160224_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='frequency',
            field=models.FloatField(default=0, null=True, verbose_name='Sum'),
        ),
        migrations.AddField(
            model_name='data',
            name='mean',
            field=models.FloatField(default=0, null=True, verbose_name='Sum'),
        ),
        migrations.AddField(
            model_name='data',
            name='sums',
            field=models.FloatField(default=0, null=True, verbose_name='Sum'),
        ),
    ]
